import {
	FETCH_USERS_LIST_REQUEST,
	FETCH_USERS_LIST_SUCCESS,
	FETCH_USERS_LIST_FAILURE,
	fetchUsers,
	ADD_SEARCH_QUERY,
	addSearchQueryAC,
	ADD_TOTAL_COUNT,
	CHANGE_PAG_PAGE,
	changePagPageAC,
} from './list';

import {
	CHANGE_PERSON,
	changePersonAC,
	fetchPersonInfo,
	FETCH_PERSON_FAILURE,
	FETCH_PERSON_REQUEST,
	FETCH_PERSON_SUCCESS,
	FETCH_PERSON_LIST_REQUEST,
	FETCH_PERSON_LIST_SUCCESS,
	FETCH_PERSON_LIST_FAILURE,
	fetchPersonList,
	CHANGE_PAG_PAGEF,
	changePagPageACC
} from './person';

export {
	FETCH_USERS_LIST_REQUEST,
	FETCH_USERS_LIST_SUCCESS,
	FETCH_USERS_LIST_FAILURE,
	fetchUsers,
	ADD_SEARCH_QUERY,
	addSearchQueryAC,
	ADD_TOTAL_COUNT,
	CHANGE_PAG_PAGE,
	changePagPageAC,
};

export {
	CHANGE_PERSON,
	changePersonAC,
	fetchPersonInfo,
	FETCH_PERSON_FAILURE,
	FETCH_PERSON_REQUEST,
	FETCH_PERSON_SUCCESS,
	FETCH_PERSON_LIST_REQUEST,
	FETCH_PERSON_LIST_SUCCESS,
	FETCH_PERSON_LIST_FAILURE,
	fetchPersonList,
	CHANGE_PAG_PAGEF,
	changePagPageACC
};
